sudo: false

language: c

addons:
  apt:
    packages:
    - libc6:i386
    - libstdc++6:i386
    
before_install:
 # Download the lua 
 - wget https://github.com/CapsAdmin/goluwa/archive/master.zip
 - unzip master.zip -d goluwa

 # Set the $PATH so gluac can be executed
 - export PATH=$PATH:`pwd`/goluwa/goluwa-master/
 
 - echo $PWD

script: bash goluwa cli --gluacheck
